## freeCodeCamp - Numpy Course

In [1]:
import numpy as np

### Basics

In [2]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


#### Get Dimension

In [4]:
a.ndim

1

In [5]:
b.ndim

2

#### Get Shape

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

#### Get Type

In [8]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

#### Get Item Size

In [10]:
a.itemsize

4

In [11]:
b.itemsize

8

#### Get Total Size

In [12]:
a.size * a.itemsize

12

In [13]:
a.nbytes

12

In [14]:
b.size * b.itemsize

48

In [15]:
b.nbytes

48

### Accessing/Changing specific elements, rows, columns, etc.

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
a.shape

(2, 7)

#### Get a specific ELEMENT

Use notation [r, c]

In [18]:
a[0,2]

3

In [19]:
a[1,-3]     # negative index notation also allowed

12

In [20]:
a[0,0], a[0,5], a[1,3], a[1,6]

(1, 6, 11, 14)

#### Get a specific ROW
Use notation [r,:]

In [21]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

#### Get a specific COLUMN
Use notation [: ,c]

In [22]:
a[: ,3]

array([ 4, 11])

#### Get specific ELEMENTS based on [start_index : end_index : step_size]

In [23]:
a[0, 1:5:2]

array([2, 4])

#### Changing/Replacing an ELEMENT

In [24]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


#### Changing/Replacing a SERIES of elements

In [25]:
a[0, 1:5] = 0
print(a)

[[ 1  0  0  0  0  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
a[0, 1:5] = [22,33,44,55]
print(a)

[[ 1 22 33 44 55  6  7]
 [ 8  9 10 11 12 20 14]]


#### 3-D example

In [27]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Get a specific ELEMENT
work outside in

In [28]:
c[0,1,1]

4

In [29]:
c[1,:,1]

array([6, 8])

In [30]:
c[:,1,:]

array([[3, 4],
       [7, 8]])

#### Changing/Replacing an ELEMENT

In [31]:
c[:,1,:] = [[33,44],[77,88]]
print(c)

[[[ 1  2]
  [33 44]]

 [[ 5  6]
  [77 88]]]


### Initializing Different Types of Arrays

#### All 0s matrix

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### All 1s matrix

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones((4,2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

#### Any other number
np.full(( 'size' ), 'number' )

In [37]:
np.full((2,3), 69)

array([[69, 69, 69],
       [69, 69, 69]])

#### Random Decimal Numbers

In [38]:
np.random.rand(4,2)

array([[0.41654673, 0.7719871 ],
       [0.11455188, 0.95618322],
       [0.31543638, 0.88287299],
       [0.98734023, 0.5307027 ]])

In [39]:
np.random.random_sample((4,2))   # Input is a shape

array([[0.61990595, 0.11727304],
       [0.76851034, 0.48754806],
       [0.9754533 , 0.16046015],
       [0.97537801, 0.80093238]])

#### Random Integer Values

In [40]:
np.random.randint(1,10, size = (4,2))

array([[8, 2],
       [1, 7],
       [3, 1],
       [6, 3]])

In [41]:
np.random.randint(-11,10, size = (4,6))

array([[  8, -10,   0,  -8,  -5,  -3],
       [ -8,  -5,   7,  -1,   1,   0],
       [ -6,  -5,   1,   1,  -6,   2],
       [  0,   4,   1,   0,   1,  -9]])

#### Identity Matrix

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Repeating an Array

In [44]:
arr = np.array([[1,2,3]])
print(arr)

[[1 2 3]]


In [45]:
rep = np.repeat(arr,3,axis=0)
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
rep = np.repeat(arr,3,axis=1)
print(rep)

[[1 1 1 2 2 2 3 3 3]]


#### Producing an Array - Assignment

In [47]:
ass = np.ones((5,5))

In [48]:
ass[1:4,1:4] = 0

In [49]:
ass[2,2] = 9

In [50]:
print(ass)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copying Arrays

In [51]:
A = np.array([1,2,3])
print(A)

[1 2 3]


In [52]:
B = A
print(B)

[1 2 3]


In [53]:
B[0] = 100
print(B)

[100   2   3]


In [54]:
print(A)

[100   2   3]


REMARK : in B = A, B simply 'points' to A and not makes a copy and stores it into B. To do that use '.copy' function

In [55]:
B = A.copy()
B[0] = 1
print('B - ',B)
print('A - ',A)

B -  [1 2 3]
A -  [100   2   3]


It doesn't change A anymore

### Mathematics

In [56]:
mat = np.array([1,2,3,4,5])
print(mat)

[1 2 3 4 5]


#### Element-wise Arithmetic

In [57]:
mat + 2          # 2 gets added to each element

array([3, 4, 5, 6, 7])

In [58]:
mat - 2          # 2 gets subtracted from each element

array([-1,  0,  1,  2,  3])

In [59]:
mat * 2          # 2 gets multiplied to each element

array([ 2,  4,  6,  8, 10])

In [60]:
mat / 2          # 2 gets divided from each element

array([0.5, 1. , 1.5, 2. , 2.5])

In [61]:
mat * mat        # Each element gets multiplied to itself

array([ 1,  4,  9, 16, 25])

In [62]:
mat2 = np.array([1,0,1,0,1])

In [63]:
mat + mat2

array([2, 2, 4, 4, 6])

In [64]:
mat - mat2

array([0, 2, 2, 4, 4])

In [65]:
mat * mat2

array([1, 0, 3, 0, 5])

#### Take the sine, cosine, etc.

In [66]:
np.sin(mat)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [67]:
np.cos(mat)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [68]:
np.tan(mat)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

#### Linear Algebra

In [69]:
king = np.ones((2,3))
print(king)

[[1. 1. 1.]
 [1. 1. 1.]]


In [70]:
queen = np.full((3,2), 2)
print(queen)

[[2 2]
 [2 2]
 [2 2]]


#### Matrix Multiplication

In [71]:
np.matmul(king,queen)

array([[6., 6.],
       [6., 6.]])

#### Finding Determinant

In [72]:
np.linalg.det(np.identity(3))

1.0

In [73]:
np.linalg.det(np.ones((3,3)))

0.0

#### Refer to this documentation for help
https://docs.scipy.org/doc/numpy/reference/routines/linalg.html
- Determinant
- Trace
- Singular Value Decomposition
- Eigen Values
- Matrix Norm
- Inverse
- Etc.

#### Statistics

In [74]:
stat = np.array([[1,2,3],[4,5,6]])
print(stat)

[[1 2 3]
 [4 5 6]]


In [75]:
np.min(stat)

1

In [76]:
np.max(stat)

6

In [77]:
np.min(stat, axis = 0)

array([1, 2, 3])

In [78]:
np.max(stat, axis = 1)

array([3, 6])

In [79]:
np.sum(stat)

21

In [80]:
np.sum(stat, axis = 0)

array([5, 7, 9])

In [81]:
np.sum(stat, axis = 1)

array([ 6, 15])

### Reorganising Arrays

In [82]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [83]:
before.shape

(2, 4)

In [84]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [85]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [86]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [87]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

#### Vertical Stacking Matrices


In [88]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [89]:
print(np.vstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


#### Horizontal Stacking Matrices

In [90]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [91]:
print(np.hstack([v1,v2]))

[1 2 3 4 5 6 7 8]


### Miscellaneous

#### Load Data From File

In [92]:
test = np.genfromtxt('test.txt', delimiter = ",")
print(test)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


#### Change data type

In [93]:
test.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### One can Index with a list in NumPy

In [94]:
test[[1,2]]

array([[  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

#### Boolean Masking and Advanced Indexing

In [95]:
test > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [96]:
test[test>50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [97]:
test[test>50].size

9

In [98]:
np.any(test>50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [99]:
np.all(test>50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [100]:
((test>50) & (test<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [101]:
(~(test>50) & (test<100))    # ~ = NOT

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [102]:
ass = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(ass)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [103]:
print(ass[2:4,0:2])

[[11 12]
 [16 17]]


In [104]:
print(ass[0,1],ass[1,2],ass[2,3],ass[3,4]) # OR

2 8 14 20


In [105]:
print(ass[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [106]:
print(ass[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
